---
title: macOS using Vagrant and VirtualBox
author: Ivan Jacob Agaloos Pesigan
---

- Download and install VirtualBox from [https://www.virtualbox.org/](https://www.virtualbox.org/).
- Download and install [Homebrew](https://brew.sh/) with the following:

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

- Install vagrant with the following:

```bash
brew install vagrant
vagrant -v
```

- Create an `Ubuntu 22.04` virtual machine using the following. Make sure that VirtualBox is running.

```bash
vagrant init bento/ubuntu-22.04
vagrant up
```

- To enter the `Ubuntu` virtual machine type:

```bash
vagrant ssh
```

- On the `Ubuntu` shell run the following to set up `Apptainer`.


```bash
cd ~
sudo apt update && sudo apt upgrade
sudo apt install -y wget
wget https://raw.githubusercontent.com/jeksterslab/dynr-wiki/main/src/build-apptainer.sh | bash
```

- Type `apptainer --version` on the terminal to verify that the installation was successful.

- To build the Singularity Image File (SIF) for the `master`[^apptainer-linux-1] branch (`dynr-rocker.sif`) run the following:

[^apptainer-linux-1]: To build the Singularity Image File (SIF) for the `arma` branch (`dynr-arma-rocker.sif`), replace `dynr-master-sif.sh` with `dynr-arma-sif.sh`

```bash
wget https://raw.githubusercontent.com/jeksterslab/dynr-wiki/main/src/dynr-master-sif.sh | bash
ls *.sif
```

- To shell into the Apptainer container type the following:

```bash
apptainer shell dynr-rocker.sif
```

- On the Apptainer shell, indicated by `Apptainer>`, type the following to run the `LinearSDE` demo.

```bash
Apptainer> Rscript -e "demo('LinearSDE', package = 'dynr')"
```

- Type `exit` to exit the Apptainer shell and go back to your `Ubuntu` shell.
