project:
  type: book
  output-dir: quarto

book:
  title: "dynr Wiki"
  author: "Ivan Jacob Agaloos Pesigan"
  date: today
  search: true
  repo-url: https://github.com/jeksterslab/dynr-wiki
  repo-actions: [edit]
  site-url: https://jeksterslab.github.io/dynr-wiki/index.html
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - .setup/quarto/intro/intro.qmd
    - part: .setup/quarto/docker/docker.qmd
      chapters: 
      - .setup/quarto/docker/docker-win.qmd
      - .setup/quarto/docker/docker-mac.qmd
      - .setup/quarto/docker/docker-image-container-tag.qmd
      - .setup/quarto/docker/docker-volumes.qmd
    - part: "Examples"
      chapters: 
      - .setup/quarto/examples/lin-growth.qmd
      - .setup/quarto/examples/var.qmd
      - .setup/quarto/examples/ou.qmd
    - .setup/quarto/references/references.qmd
  appendices:
    - .setup/quarto/session/session.qmd

bibliography: .setup/quarto/bib/quarto.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

format:
  html:
    theme:
      - flatly
      - custom.scss
    number-sections: false
    code-link: true
