project:
  type: book
  output-dir: docs

book:
  title: "dynr Wiki"
  author: "Ivan Jacob Agaloos Pesigan"
  date: today
  search: true
  repo-url: https://github.com/jeksterslab/dynr-wiki
  repo-actions: [edit]
  site-url: https://jeksterslab.github.io/dynr-wiki/index.html
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - content/intro/intro.qmd
    - part: content/docker/docker.qmd
      chapters: 
      - content/docker/docker-win.qmd
      - content/docker/docker-mac.qmd
    - part: "Examples"
      chapters: 
      - content/examples/var.qmd
    - content/references/references.qmd
  appendices:
    - content/session/session.qmd

bibliography: content/references/references.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

format:
  html:
    theme:
      - flatly
      - custom.scss
    number-sections: false
