---
title: Windows using WSL 2
author: Ivan Jacob Agaloos Pesigan
---

In this tutorial, we will go through the necessary steps to launch the `dynr` Docker container on Windows 10. Installation on Windows 11 should be similar.

<!--
::: callout-note
For a better terminal experience, you can, optionally, install the `Windows Terminal` from the `Microsoft Store`.  
:::
-->

## Installing Windows Subsystem for Linux (WSL)

- Search for `PowerShell` or `Command Prompt`. Right click to run as an administrator, then type the following:

```powershell
wsl --install --distribution Ubuntu
```

<!--
-  In `PowerShell`[^docker-win-1], type the following:

```powershell
wsl --install --distribution Ubuntu

[^docker-win-1]: Run all instances of PowerShell as administration.
```
-->

::: callout-note
There are times when the operating system requires a restart. After restarting, when the installation is successful, a new application `Ubuntu` will be available. Launch this application to continue.
:::

-  When prompted:
    -  Enter new UNIX username:
    -  New password:
    -  Retype new password:
-  You should see a prompt similar to the following which indicates that you are inside the newly installed `Ubuntu` instance. In the prompt, type `exit` to exit `Ubuntu`.

```bash
USER@HOST:~$
```

-  You might need to update the kernel. You can do this with the following:
    -  Download the Linux kernel update package from [https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)
    -  Double-click `wsl_update_x64.msi` to update the kernel.
-  A system restart might be a good idea for all the changes to take effect.

If the above instructions fail, you might be using an older version of Windows. See [https://learn.microsoft.com/en-us/windows/wsl/install-manual](https://learn.microsoft.com/en-us/windows/wsl/install-manual) for more details on how to manually install WSL.

## Installing Docker Desktop

-  Download the the appropriate Docker Desktop for Windows from [https://www.docker.com/products/docker-desktop/](https://www.docker.com/products/docker-desktop/).
-  Double-click `Docker Desktop Installer.exe` to install `Docker Desktop`.
-  Launch `Docker Desktop`.
    -  Click the `Accept` button to accept the terms of service to continue.
    -  You may continue without creating an account or signing in.

## Running the dynr Docker Container

-  Launch `Docker Desktop`.
-  In `PowerShell`, type the following to pull the latest Docker image:

```powershell
docker pull jeksterslab/dynr-rocker:latest
```

-  In `PowerShell`, type the following to launch `Rstudio Server`[^docker-win-1]:

[^docker-win-1]: Note for developers only: Replace `jeksterslab/dynr-rocker` with `jeksterslab/dynr-arma-rocker` to use the `arma` branch.

```powershell
docker run --rm -ti -e PASSWORD=yourpassword -p 127.0.0.1:8787:8787 jeksterslab/dynr-rocker
```

-  Open http://localhost:8787 on your web browser to launch `Rstudio Server`.
    -  username: rstudio
    -  password: yourpassword[^docker-win-2]

[^docker-win-2]: You can change the password by replacing `yourpassword` in `PASSWORD=yourpassword`.

<!--
-  In `PowerShell` type the following to pull the latest Docker image:

```powershell
docker pull jeksterslab/dynr-rocker:latest
```
-->
