---
title: macOS
author: Ivan Jacob Agaloos Pesigan
---

In this tutorial, we will go through the necessary steps to launch the `dynr` Docker container on macOS.

## Installation Video Tutorial

[**Click here for a video tutorial of the installation process.**](https://psu.mediaspace.kaltura.com/media/Mac%3A%20Tutorial%20on%20installing%20dynr%20Docker%20/1_2ln6jawo){target="_blank"}

<!--
::: callout-note
For a better terminal experience, you can, optionally, install `iTerm2`.  
:::
-->

## Installing Docker Desktop

<!--
-  Download the the appropriate Docker Desktop for macOS (Intel Chip vs. Apple Chip) from [https://www.docker.com/products/docker-desktop/](https://www.docker.com/products/docker-desktop/).
-  Double-click `Desktop.dmg` to install `Docker Desktop`.
-  Drag `Docker.app` to the `Applications` folder.
-  Launch `Docker` from the `Launchpad`.
    -  The system would ask for your macOS user password.
    -  Click the `Accept` button to accept the terms of service to continue.
-->

-  Download the the appropriate Docker Desktop for macOS (Intel Chip vs. Apple Chip) from [https://www.docker.com/products/docker-desktop/](https://www.docker.com/products/docker-desktop/).
-  Double-click `Desktop.dmg` to install `Docker Desktop`.
-  Drag `Docker.app` to the `Applications` folder.
-  Launch `Docker` from the `Launchpad`.
    -  Choose `Use recommended settings (requires password)` and provide your macOS user password.
    -  Click the `Accept` button to accept the terms of service to continue.
    -  You may continue without creating an account or signing in.

## Running the dynr Docker Container

-  Launch `Docker Desktop`.
-  On your macOS terminal, type the following to pull the latest Docker image:

```bash
docker pull jeksterslab/dynr-rocker:latest
```

-  On your macOS terminal, type the following to launch `Rstudio Server`[^dynr-rocker-mac-1]:

[^dynr-rocker-mac-1]: Note for developers only: Replace `jeksterslab/dynr-rocker` with `jeksterslab/dynr-arma-rocker` to use the `arma` branch.

```bash
docker run --rm -ti -e PASSWORD=yourpassword -p 127.0.0.1:8787:8787 jeksterslab/dynr-rocker
```

-  Open http://localhost:8787 on your web browser to launch `Rstudio Server`.
    -  username: rstudio
    -  password: yourpassword[^docker-mac-2]

[^docker-mac-2]: You can change the password by replacing `yourpassword` in `PASSWORD=yourpassword`.
